import type {
  JobProfile,
  Candidate,
  WhatsAppThread,
  Notification,
} from '@/types'

// ─── JOB PROFILES ──────────────────────────────────────────────────────────

export const mockJobProfiles: JobProfile[] = [
  {
    id: 'job-001',
    title: 'Senior Site Engineer',
    department: 'Engineering',
    location: 'Dubai, UAE',
    openings: 2,
    status: 'active',
    description:
      'We are seeking an experienced Senior Site Engineer to oversee construction activities on high-rise residential and mixed-use developments across Dubai.',
    mandatoryCriteria: {
      degreeRequired: true,
      minDegreeLevel: 'bachelor',
      degreeFields: ['Civil Engineering', 'Structural Engineering'],
      yearsMin: 8,
      yearsMax: 20,
      certifications: ['PMP', 'FIDIC'],
      uaeDrivingLicense: true,
      rightToWorkUAE: true,
      allowedNationalities: ['Any'],
    },
    preferredCriteria: {
      skills: [
        { id: 'sk-1', name: 'AutoCAD', weight: 5 },
        { id: 'sk-2', name: 'MS Project', weight: 4 },
        { id: 'sk-3', name: 'Primavera P6', weight: 4 },
        { id: 'sk-4', name: 'BIM / Revit', weight: 3 },
      ],
      industryBackground: ['Construction', 'Real Estate'],
      employerType: ['Main Contractor', 'Developer'],
      languages: ['English', 'Arabic'],
      relevantProjects: ['High-rise residential', 'Mixed-use development'],
    },
    scoringWeights: {
      yearsExperience: 25,
      technicalSkills: 30,
      industryBackground: 20,
      certifications: 15,
      languages: 10,
    },
    templateUsed: 'Senior Site Engineer',
    createdAt: '2024-11-01T08:00:00Z',
    updatedAt: '2024-11-15T10:30:00Z',
    stats: {
      uploaded: 24,
      scored: 24,
      shortlisted: 8,
      eliminated: 6,
      avgScore: 68,
      scoreDistribution: [
        { range: '0-20', count: 1 },
        { range: '21-40', count: 2 },
        { range: '41-60', count: 7 },
        { range: '61-80', count: 9 },
        { range: '81-100', count: 5 },
      ],
    },
  },
  {
    id: 'job-002',
    title: 'Project Manager',
    department: 'Operations',
    location: 'Abu Dhabi, UAE',
    openings: 1,
    status: 'active',
    description:
      'Lead end-to-end real estate development projects from land acquisition through to handover, managing multi-disciplinary teams and stakeholder relations.',
    mandatoryCriteria: {
      degreeRequired: true,
      minDegreeLevel: 'bachelor',
      degreeFields: ['Civil Engineering', 'Architecture', 'Project Management'],
      yearsMin: 10,
      yearsMax: 25,
      certifications: ['PMP'],
      uaeDrivingLicense: false,
      rightToWorkUAE: true,
      allowedNationalities: ['Any'],
    },
    preferredCriteria: {
      skills: [
        { id: 'sk-5', name: 'Stakeholder Management', weight: 5 },
        { id: 'sk-6', name: 'Risk Management', weight: 5 },
        { id: 'sk-7', name: 'Primavera P6', weight: 3 },
        { id: 'sk-8', name: 'Budget Control', weight: 4 },
        { id: 'sk-9', name: 'FIDIC Contracts', weight: 4 },
      ],
      industryBackground: ['Real Estate', 'Construction', 'Infrastructure'],
      employerType: ['Developer', 'Main Contractor', 'Consultant'],
      languages: ['English', 'Arabic'],
      relevantProjects: ['Mixed-use development', 'Hotel & hospitality', 'Villa communities'],
    },
    scoringWeights: {
      yearsExperience: 20,
      technicalSkills: 25,
      industryBackground: 20,
      certifications: 20,
      languages: 15,
    },
    templateUsed: 'Project Manager',
    createdAt: '2024-10-15T09:00:00Z',
    updatedAt: '2024-11-10T14:20:00Z',
    stats: {
      uploaded: 31,
      scored: 31,
      shortlisted: 9,
      eliminated: 8,
      avgScore: 62,
      scoreDistribution: [
        { range: '0-20', count: 2 },
        { range: '21-40', count: 4 },
        { range: '41-60', count: 10 },
        { range: '61-80', count: 11 },
        { range: '81-100', count: 4 },
      ],
    },
  },
  {
    id: 'job-003',
    title: 'Quantity Surveyor',
    department: 'Commercial',
    location: 'Dubai, UAE',
    openings: 3,
    status: 'paused',
    description:
      'Responsible for cost estimation, contract administration, and commercial management on large-scale infrastructure projects.',
    mandatoryCriteria: {
      degreeRequired: true,
      minDegreeLevel: 'bachelor',
      degreeFields: ['Quantity Surveying', 'Civil Engineering', 'Construction Management'],
      yearsMin: 5,
      yearsMax: 15,
      certifications: ['RICS'],
      uaeDrivingLicense: false,
      rightToWorkUAE: true,
      allowedNationalities: ['Any'],
    },
    preferredCriteria: {
      skills: [
        { id: 'sk-10', name: 'Cost Estimation', weight: 5 },
        { id: 'sk-11', name: 'Contract Administration', weight: 5 },
        { id: 'sk-12', name: 'CostX / Candy', weight: 4 },
        { id: 'sk-13', name: 'Value Engineering', weight: 3 },
      ],
      industryBackground: ['Infrastructure', 'Construction', 'Oil & Gas'],
      employerType: ['Consultant', 'Main Contractor', 'Government'],
      languages: ['English'],
      relevantProjects: ['Metro infrastructure', 'Highway', 'Utilities'],
    },
    scoringWeights: {
      yearsExperience: 20,
      technicalSkills: 35,
      industryBackground: 20,
      certifications: 15,
      languages: 10,
    },
    createdAt: '2024-09-20T11:00:00Z',
    updatedAt: '2024-10-30T16:45:00Z',
    stats: {
      uploaded: 18,
      scored: 18,
      shortlisted: 5,
      eliminated: 4,
      avgScore: 71,
      scoreDistribution: [
        { range: '0-20', count: 0 },
        { range: '21-40', count: 2 },
        { range: '41-60', count: 4 },
        { range: '61-80', count: 8 },
        { range: '81-100', count: 4 },
      ],
    },
  },
]

// ─── CANDIDATES — Job 001 (Senior Site Engineer) ────────────────────────────

export const mockCandidatesJob001: Candidate[] = [
  {
    id: 'cand-001',
    jobProfileId: 'job-001',
    name: 'Ahmed Al-Rashidi',
    email: 'ahmed.rashidi@email.com',
    phone: '+971 50 123 4567',
    nationality: 'Emirati',
    age: 38,
    languages: ['Arabic', 'English'],
    currentTitle: 'Senior Site Engineer',
    currentCompany: 'ALEC Engineering',
    yearsExperience: 14,
    degreeLevel: 'bachelor',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'UAE University',
        degree: 'Bachelor of Science',
        field: 'Civil Engineering',
        year: 2010,
        grade: 'Distinction',
      },
    ],
    experience: [
      {
        company: 'ALEC Engineering',
        title: 'Senior Site Engineer',
        startDate: '2019-03',
        endDate: null,
        duration: '5 yr 8 mo',
        description: 'Overseeing construction of 42-storey mixed-use tower in Business Bay.',
      },
      {
        company: 'Arabtec Construction',
        title: 'Site Engineer',
        startDate: '2014-06',
        endDate: '2019-02',
        duration: '4 yr 8 mo',
        description: 'On-site supervision of residential villa communities in Meydan.',
      },
      {
        company: 'Al Naboodah Construction',
        title: 'Junior Engineer',
        startDate: '2010-09',
        endDate: '2014-05',
        duration: '3 yr 8 mo',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.95 },
      { name: 'MS Project', matched: true, confidence: 0.9 },
      { name: 'Primavera P6', matched: true, confidence: 0.88 },
      { name: 'BIM / Revit', matched: true, confidence: 0.75 },
    ],
    certifications: ['PMP', 'FIDIC Yellow Book', 'UAE NOC Holder'],
    status: 'shortlisted',
    finalScore: 91,
    criterionScores: {
      yearsExperience: { score: 95, justification: '14 years directly relevant experience in UAE construction, exceeding the 8-year minimum.' },
      technicalSkills: { score: 88, justification: 'Strong proficiency in all required tools. AutoCAD and Primavera P6 mentioned with specific project examples.' },
      industryBackground: { score: 95, justification: 'Entire career in GCC construction and real estate development with major tier-1 contractors.' },
      certifications: { score: 90, justification: 'Holds PMP and FIDIC certifications as required. UAE NOC holder is a bonus.' },
      languages: { score: 90, justification: 'Native Arabic and professional English — ideal for UAE market.' },
    },
    aiSummary:
      'Ahmed is an outstanding candidate with 14 years of UAE-based construction experience at tier-1 contractors. His combination of PMP, FIDIC certifications, and hands-on high-rise experience makes him a near-perfect fit. The only minor gap is limited BIM experience relative to the role requirements.',
    extractionConfidence: 0.97,
    shortlistedAt: '2024-11-16T09:00:00Z',
    createdAt: '2024-11-15T08:30:00Z',
    cvFilePath: 'cvs/ahmed-rashidi.pdf',
  },
  {
    id: 'cand-002',
    jobProfileId: 'job-001',
    name: 'Priya Nair',
    email: 'p.nair@outlook.com',
    phone: '+971 55 987 6543',
    nationality: 'Indian',
    age: 33,
    languages: ['English', 'Hindi', 'Malayalam'],
    currentTitle: 'Site Engineer',
    currentCompany: 'Shapoorji Pallonji',
    yearsExperience: 9,
    degreeLevel: 'master',
    degreeField: 'Structural Engineering',
    education: [
      {
        institution: 'Indian Institute of Technology Bombay',
        degree: 'Master of Technology',
        field: 'Structural Engineering',
        year: 2017,
        grade: 'First Class',
      },
      {
        institution: 'NIT Calicut',
        degree: 'Bachelor of Technology',
        field: 'Civil Engineering',
        year: 2015,
      },
    ],
    experience: [
      {
        company: 'Shapoorji Pallonji',
        title: 'Site Engineer',
        startDate: '2020-01',
        endDate: null,
        duration: '4 yr 10 mo',
        description: 'Structural coordination on Sobha Hartland Phase 2 villas.',
      },
      {
        company: 'L&T Construction',
        title: 'Graduate Engineer',
        startDate: '2017-07',
        endDate: '2019-12',
        duration: '2 yr 5 mo',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.92 },
      { name: 'MS Project', matched: true, confidence: 0.85 },
      { name: 'Primavera P6', matched: false, confidence: 0.3 },
      { name: 'BIM / Revit', matched: true, confidence: 0.88 },
    ],
    certifications: ['PMP', 'LEED AP'],
    status: 'shortlisted',
    finalScore: 82,
    criterionScores: {
      yearsExperience: { score: 78, justification: '9 years experience, within the required range. Masters degree partially compensates for less hands-on seniority.' },
      technicalSkills: { score: 85, justification: 'Strong in AutoCAD and BIM. Primavera P6 experience appears limited — not mentioned directly.' },
      industryBackground: { score: 80, justification: 'Good residential real estate experience in UAE with reputable Indian contractors active in the GCC.' },
      certifications: { score: 85, justification: 'PMP certified. LEED AP is a bonus. FIDIC certification absent — minor gap.' },
      languages: { score: 70, justification: 'English proficient but no Arabic. For UAE market this is a moderate gap.' },
    },
    aiSummary:
      'Priya is a strong candidate with an IIT Bombay Master\'s in Structural Engineering and solid UAE site experience. Her BIM skills and PMP certification are real assets. The absence of Primavera P6 and Arabic language skills are the main differentiators vs top-ranked candidates.',
    extractionConfidence: 0.94,
    shortlistedAt: '2024-11-16T11:00:00Z',
    createdAt: '2024-11-15T09:00:00Z',
    cvFilePath: 'cvs/priya-nair.pdf',
  },
  {
    id: 'cand-003',
    jobProfileId: 'job-001',
    name: 'Omar Khalil',
    email: 'omar.k@gmail.com',
    phone: '+971 52 456 7890',
    nationality: 'Egyptian',
    age: 41,
    languages: ['Arabic', 'English'],
    currentTitle: 'Senior Site Manager',
    currentCompany: 'Six Construct',
    yearsExperience: 17,
    degreeLevel: 'bachelor',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'Cairo University',
        degree: 'Bachelor of Science',
        field: 'Civil Engineering',
        year: 2007,
      },
    ],
    experience: [
      {
        company: 'Six Construct',
        title: 'Senior Site Manager',
        startDate: '2018-04',
        endDate: null,
        duration: '6 yr 7 mo',
        description: 'Managing construction of Louvre Abu Dhabi expansion and Etihad Museum extensions.',
      },
      {
        company: 'Consolidated Contractors Company',
        title: 'Site Engineer',
        startDate: '2012-01',
        endDate: '2018-03',
        duration: '6 yr 2 mo',
      },
      {
        company: 'Orascom Construction',
        title: 'Junior Civil Engineer',
        startDate: '2007-09',
        endDate: '2011-12',
        duration: '4 yr 3 mo',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.9 },
      { name: 'MS Project', matched: true, confidence: 0.88 },
      { name: 'Primavera P6', matched: true, confidence: 0.92 },
      { name: 'BIM / Revit', matched: false, confidence: 0.2 },
    ],
    certifications: ['PMP', 'FIDIC Gold Book', 'OSHA 30'],
    status: 'shortlisted',
    finalScore: 88,
    criterionScores: {
      yearsExperience: { score: 97, justification: '17 years of highly relevant experience including landmark projects in the UAE.' },
      technicalSkills: { score: 82, justification: 'Excellent in scheduling tools and AutoCAD. BIM/Revit appears absent — growing requirement for the role.' },
      industryBackground: { score: 92, justification: 'Pan-GCC experience with premium tier-1 contractors on iconic projects.' },
      certifications: { score: 90, justification: 'PMP + FIDIC + OSHA — strong credentials package.' },
      languages: { score: 90, justification: 'Bilingual Arabic/English — excellent fit for UAE client-facing role.' },
    },
    aiSummary:
      'Omar is a highly experienced senior professional with 17 years across Egypt and the UAE\'s most prestigious construction projects. His project portfolio (Louvre expansion, Etihad Museum) demonstrates high-calibre delivery capability. The only notable gap is the absence of BIM/Revit experience, which is increasingly expected at this seniority level.',
    extractionConfidence: 0.96,
    shortlistedAt: '2024-11-16T10:00:00Z',
    createdAt: '2024-11-15T08:45:00Z',
    cvFilePath: 'cvs/omar-khalil.pdf',
  },
  {
    id: 'cand-004',
    jobProfileId: 'job-001',
    name: 'James Whitmore',
    email: 'j.whitmore@hotmail.com',
    phone: '+971 50 321 9876',
    nationality: 'British',
    age: 45,
    languages: ['English'],
    currentTitle: 'Construction Manager',
    currentCompany: 'Laing O\'Rourke',
    yearsExperience: 21,
    degreeLevel: 'master',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'University of Leeds',
        degree: 'Master of Engineering',
        field: 'Civil Engineering',
        year: 2003,
        grade: '2:1',
      },
    ],
    experience: [
      {
        company: 'Laing O\'Rourke',
        title: 'Construction Manager',
        startDate: '2016-09',
        endDate: null,
        duration: '8 yr 2 mo',
        description: 'Overseeing delivery of Expo City Dubai infrastructure projects.',
      },
      {
        company: 'Carillion',
        title: 'Senior Site Engineer',
        startDate: '2010-01',
        endDate: '2016-08',
        duration: '6 yr 7 mo',
      },
      {
        company: 'Skanska UK',
        title: 'Site Engineer',
        startDate: '2003-07',
        endDate: '2009-12',
        duration: '6 yr 5 mo',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.88 },
      { name: 'MS Project', matched: true, confidence: 0.92 },
      { name: 'Primavera P6', matched: true, confidence: 0.85 },
      { name: 'BIM / Revit', matched: true, confidence: 0.82 },
    ],
    certifications: ['PMP', 'FIDIC Yellow Book', 'CIOB Member', 'PRINCE2'],
    status: 'under_review',
    finalScore: 78,
    criterionScores: {
      yearsExperience: { score: 90, justification: '21 years experience, strongly exceeds minimum. Risk of being overqualified for a site engineer role.' },
      technicalSkills: { score: 88, justification: 'Comprehensive technical toolkit including BIM.' },
      industryBackground: { score: 72, justification: 'Mix of UK and UAE experience. UAE market exposure is more recent and limited to infrastructure vs residential high-rise.' },
      certifications: { score: 95, justification: 'Exceptional certification profile — PMP, FIDIC, CIOB, PRINCE2.' },
      languages: { score: 60, justification: 'English only. UAE market increasingly values Arabic for client interactions.' },
    },
    aiSummary:
      'James is an overqualified candidate with 21 years of international construction experience. His credentials are excellent but his salary expectations may exceed the role\'s band, and his background leans toward infrastructure rather than high-rise residential. Worth interviewing for a more senior position.',
    extractionConfidence: 0.95,
    createdAt: '2024-11-15T10:00:00Z',
    cvFilePath: 'cvs/james-whitmore.pdf',
  },
  {
    id: 'cand-005',
    jobProfileId: 'job-001',
    name: 'Fatima Al-Zahra',
    email: 'f.alzahra@yahoo.com',
    phone: '+971 54 654 3210',
    nationality: 'Moroccan',
    age: 29,
    languages: ['Arabic', 'French', 'English'],
    currentTitle: 'Site Engineer',
    currentCompany: 'Multiplex',
    yearsExperience: 5,
    degreeLevel: 'bachelor',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'École Mohammadia d\'Ingénieurs',
        degree: 'Bachelor of Engineering',
        field: 'Civil Engineering',
        year: 2019,
      },
    ],
    experience: [
      {
        company: 'Multiplex',
        title: 'Site Engineer',
        startDate: '2021-06',
        endDate: null,
        duration: '3 yr 5 mo',
        description: 'Quality control and supervision on Creek Harbour residential towers.',
      },
      {
        company: 'BESIX',
        title: 'Graduate Engineer',
        startDate: '2019-09',
        endDate: '2021-05',
        duration: '1 yr 8 mo',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.85 },
      { name: 'MS Project', matched: true, confidence: 0.7 },
      { name: 'Primavera P6', matched: false, confidence: 0.25 },
      { name: 'BIM / Revit', matched: true, confidence: 0.78 },
    ],
    certifications: ['PMP Candidate'],
    status: 'scored',
    finalScore: 58,
    criterionScores: {
      yearsExperience: { score: 52, justification: '5 years experience — below the 8-year minimum. Does not meet mandatory threshold.' },
      technicalSkills: { score: 72, justification: 'Good AutoCAD and BIM skills. Primavera P6 is absent. MS Project exposure appears basic.' },
      industryBackground: { score: 65, justification: 'UAE high-rise residential experience with Multiplex is relevant, though tenure is short.' },
      certifications: { score: 40, justification: 'No completed certifications. PMP candidacy noted but not achieved.' },
      languages: { score: 85, justification: 'Trilingual Arabic/French/English — above average for the role.' },
    },
    aiSummary:
      'Fatima shows strong potential with good technical foundations and relevant UAE project experience. However, she falls below the mandatory 8-year experience threshold and lacks the required PMP certification. She may be a strong candidate in 2-3 years.',
    extractionConfidence: 0.91,
    createdAt: '2024-11-15T11:00:00Z',
    cvFilePath: 'cvs/fatima-alzahra.pdf',
  },
  {
    id: 'cand-006',
    jobProfileId: 'job-001',
    name: 'Raj Kumar Singh',
    email: 'raj.singh@gmail.com',
    phone: '+971 56 789 0123',
    nationality: 'Indian',
    age: 36,
    languages: ['English', 'Hindi'],
    currentTitle: 'Project Engineer',
    currentCompany: 'Samsung C&T',
    yearsExperience: 11,
    degreeLevel: 'bachelor',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'Delhi Technological University',
        degree: 'Bachelor of Engineering',
        field: 'Civil Engineering',
        year: 2013,
      },
    ],
    experience: [
      {
        company: 'Samsung C&T',
        title: 'Project Engineer',
        startDate: '2019-02',
        endDate: null,
        duration: '5 yr 9 mo',
        description: 'MEP coordination and civil works on The Address Sky View hotel.',
      },
      {
        company: 'L&T Construction',
        title: 'Site Engineer',
        startDate: '2015-08',
        endDate: '2019-01',
        duration: '3 yr 5 mo',
      },
      {
        company: 'Gammon India',
        title: 'Graduate Engineer',
        startDate: '2013-07',
        endDate: '2015-07',
        duration: '2 yr',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.9 },
      { name: 'MS Project', matched: true, confidence: 0.85 },
      { name: 'Primavera P6', matched: true, confidence: 0.8 },
      { name: 'BIM / Revit', matched: false, confidence: 0.3 },
    ],
    certifications: ['PMP'],
    status: 'shortlisted',
    finalScore: 75,
    criterionScores: {
      yearsExperience: { score: 82, justification: '11 years experience, comfortably within the required range.' },
      technicalSkills: { score: 78, justification: 'Good scheduling and CAD skills. BIM experience is lacking for a modern construction role.' },
      industryBackground: { score: 75, justification: 'Hospitality and high-rise experience in Dubai is relevant but primarily MEP focused rather than civil.' },
      certifications: { score: 80, justification: 'PMP certified. FIDIC exposure absent.' },
      languages: { score: 65, justification: 'English and Hindi only. Arabic language skills would strengthen GCC client relationships.' },
    },
    aiSummary:
      'Raj is a competent mid-level engineer with strong scheduling and coordination skills demonstrated on premium Dubai hospitality projects. His PMP certification and 11 years of experience meet core requirements, though the absence of FIDIC exposure and BIM skills are minor gaps relative to top candidates.',
    extractionConfidence: 0.93,
    shortlistedAt: '2024-11-16T14:00:00Z',
    createdAt: '2024-11-15T12:00:00Z',
    cvFilePath: 'cvs/raj-singh.pdf',
  },
  {
    id: 'cand-007',
    jobProfileId: 'job-001',
    name: 'Mohammed Al-Qahtani',
    email: 'm.qahtani@hotmail.com',
    phone: '+966 50 123 4567',
    nationality: 'Saudi',
    age: 32,
    languages: ['Arabic', 'English'],
    currentTitle: 'Civil Engineer',
    currentCompany: 'Saudi Aramco',
    yearsExperience: 7,
    degreeLevel: 'bachelor',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'King Fahd University of Petroleum & Minerals',
        degree: 'Bachelor of Science',
        field: 'Civil Engineering',
        year: 2017,
        grade: 'Excellent',
      },
    ],
    experience: [
      {
        company: 'Saudi Aramco',
        title: 'Civil Engineer',
        startDate: '2020-01',
        endDate: null,
        duration: '4 yr 10 mo',
        description: 'Infrastructure and facility construction at Ras Tanura refinery.',
      },
      {
        company: 'SABIC Engineering',
        title: 'Graduate Engineer',
        startDate: '2017-09',
        endDate: '2019-12',
        duration: '2 yr 3 mo',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.88 },
      { name: 'MS Project', matched: true, confidence: 0.75 },
      { name: 'Primavera P6', matched: false, confidence: 0.4 },
      { name: 'BIM / Revit', matched: false, confidence: 0.2 },
    ],
    certifications: [],
    status: 'eliminated',
    finalScore: 38,
    eliminationReason: 'Does not meet mandatory 8-year experience requirement (7 years). No required certifications (PMP, FIDIC).',
    criterionScores: {
      yearsExperience: { score: 70, justification: '7 years — 1 year below the mandatory minimum.', passFail: 'fail' },
      technicalSkills: { score: 60, justification: 'Basic tool proficiency. No Primavera P6 or BIM mentioned.' },
      industryBackground: { score: 45, justification: 'Oil & gas / industrial background. Limited residential or high-rise construction exposure.' },
      certifications: { score: 0, justification: 'No certifications held. PMP and FIDIC are mandatory.', passFail: 'fail' },
      languages: { score: 90, justification: 'Native Arabic and professional English.' },
    },
    aiSummary:
      'Mohammed fails mandatory experience and certification thresholds. His 7 years of experience falls below the 8-year minimum, and he holds no professional certifications. His Saudi Aramco background is prestigious but not aligned with residential high-rise construction.',
    extractionConfidence: 0.89,
    createdAt: '2024-11-15T13:00:00Z',
    cvFilePath: 'cvs/mohammed-qahtani.pdf',
  },
  {
    id: 'cand-008',
    jobProfileId: 'job-001',
    name: 'Yuki Tanaka',
    email: 'y.tanaka@construction.jp',
    phone: '+81 90 1234 5678',
    nationality: 'Japanese',
    age: 44,
    languages: ['Japanese', 'English'],
    currentTitle: 'Senior Engineer',
    currentCompany: 'Obayashi Corporation',
    yearsExperience: 19,
    degreeLevel: 'master',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'University of Tokyo',
        degree: 'Master of Engineering',
        field: 'Civil Engineering',
        year: 2005,
      },
    ],
    experience: [
      {
        company: 'Obayashi Corporation',
        title: 'Senior Engineer',
        startDate: '2010-04',
        endDate: null,
        duration: '14 yr 7 mo',
        description: 'Structural engineering on high-rise commercial developments in Tokyo and Osaka.',
      },
      {
        company: 'Kajima Corporation',
        title: 'Engineer',
        startDate: '2005-04',
        endDate: '2010-03',
        duration: '5 yr',
      },
    ],
    skills: [
      { name: 'AutoCAD', matched: true, confidence: 0.85 },
      { name: 'MS Project', matched: true, confidence: 0.8 },
      { name: 'Primavera P6', matched: false, confidence: 0.2 },
      { name: 'BIM / Revit', matched: true, confidence: 0.9 },
    ],
    certifications: ['JSCE Certified Engineer', 'PMP'],
    status: 'eliminated',
    finalScore: 42,
    eliminationReason: 'No UAE Right to Work. Salary expectations likely misaligned with market. No UAE/GCC experience.',
    criterionScores: {
      yearsExperience: { score: 92, justification: '19 years of senior engineering experience.', passFail: 'pass' },
      technicalSkills: { score: 82, justification: 'Strong BIM and AutoCAD. Limited Primavera P6.' },
      industryBackground: { score: 30, justification: 'Entirely Japan-based experience. No GCC or Middle East exposure.', passFail: 'fail' },
      certifications: { score: 70, justification: 'PMP and JSCE certified. FIDIC absent.' },
      languages: { score: 30, justification: 'English and Japanese only. No Arabic. Significant gap for UAE client work.' },
    },
    aiSummary:
      'Yuki is technically accomplished with exceptional Japanese high-rise experience, but lacks UAE Right to Work eligibility and has no GCC market exposure. Cultural and language barriers are significant for client-facing site management in the UAE.',
    extractionConfidence: 0.88,
    createdAt: '2024-11-15T14:00:00Z',
    cvFilePath: 'cvs/yuki-tanaka.pdf',
  },
]

// ─── CANDIDATES — Job 002 (Project Manager) ─────────────────────────────────

export const mockCandidatesJob002: Candidate[] = [
  {
    id: 'cand-101',
    jobProfileId: 'job-002',
    name: 'Sarah Al-Mansoori',
    email: 's.mansoori@email.ae',
    phone: '+971 50 456 7890',
    nationality: 'Emirati',
    age: 40,
    languages: ['Arabic', 'English'],
    currentTitle: 'Senior Project Manager',
    currentCompany: 'Emaar Properties',
    yearsExperience: 16,
    degreeLevel: 'master',
    degreeField: 'Project Management',
    education: [
      {
        institution: 'British University in Dubai',
        degree: 'Master of Science',
        field: 'Project Management',
        year: 2012,
        grade: 'Distinction',
      },
      {
        institution: 'UAE University',
        degree: 'Bachelor of Science',
        field: 'Architecture',
        year: 2009,
      },
    ],
    experience: [
      {
        company: 'Emaar Properties',
        title: 'Senior Project Manager',
        startDate: '2017-01',
        endDate: null,
        duration: '7 yr 10 mo',
        description: 'Leading delivery of Emaar Beachfront Phase 3 — 12 residential towers, AED 4.2B value.',
      },
      {
        company: 'Meydan Group',
        title: 'Project Manager',
        startDate: '2012-06',
        endDate: '2016-12',
        duration: '4 yr 6 mo',
      },
      {
        company: 'Dubai Municipality',
        title: 'Project Coordinator',
        startDate: '2009-09',
        endDate: '2012-05',
        duration: '2 yr 8 mo',
      },
    ],
    skills: [
      { name: 'Stakeholder Management', matched: true, confidence: 0.97 },
      { name: 'Risk Management', matched: true, confidence: 0.95 },
      { name: 'Primavera P6', matched: true, confidence: 0.92 },
      { name: 'Budget Control', matched: true, confidence: 0.96 },
      { name: 'FIDIC Contracts', matched: true, confidence: 0.9 },
    ],
    certifications: ['PMP', 'PRINCE2 Practitioner', 'PMI-RMP'],
    status: 'shortlisted',
    finalScore: 95,
    criterionScores: {
      yearsExperience: { score: 98, justification: '16 years of progressive project management experience, entirely in UAE real estate development.' },
      technicalSkills: { score: 96, justification: 'Exceptional across all required skills with evidence of application on multi-billion dirham projects.' },
      industryBackground: { score: 98, justification: 'Emaar and Meydan — two of the most prestigious UAE developers. Perfect alignment.' },
      certifications: { score: 97, justification: 'PMP, PRINCE2, and PMI-RMP — exceptional credentials package.' },
      languages: { score: 95, justification: 'Native Arabic and professional English. Ideal for UAE government and client relations.' },
    },
    aiSummary:
      'Sarah is an exceptional candidate — a rare Emirati senior PM with 16 years at UAE\'s top developers. Her Emaar Beachfront experience managing AED 4.2B worth of delivery is directly on target. Certification profile is outstanding. Strongly recommend for first-round interview.',
    extractionConfidence: 0.98,
    shortlistedAt: '2024-11-11T09:00:00Z',
    createdAt: '2024-11-10T08:00:00Z',
    cvFilePath: 'cvs/sarah-mansoori.pdf',
  },
  {
    id: 'cand-102',
    jobProfileId: 'job-002',
    name: 'David Okafor',
    email: 'david.okafor@pm.com',
    phone: '+971 55 123 9876',
    nationality: 'Nigerian',
    age: 47,
    languages: ['English', 'French'],
    currentTitle: 'Project Director',
    currentCompany: 'Hill International',
    yearsExperience: 23,
    degreeLevel: 'master',
    degreeField: 'Civil Engineering',
    education: [
      {
        institution: 'University of Lagos',
        degree: 'Master of Science',
        field: 'Civil Engineering',
        year: 2001,
      },
      {
        institution: 'Obafemi Awolowo University',
        degree: 'Bachelor of Engineering',
        field: 'Civil Engineering',
        year: 1999,
      },
    ],
    experience: [
      {
        company: 'Hill International',
        title: 'Project Director',
        startDate: '2015-03',
        endDate: null,
        duration: '9 yr 8 mo',
        description: 'Programme management for Abu Dhabi Urban Planning Council mega-projects.',
      },
      {
        company: 'AECOM',
        title: 'Senior Project Manager',
        startDate: '2009-01',
        endDate: '2015-02',
        duration: '6 yr 1 mo',
      },
    ],
    skills: [
      { name: 'Stakeholder Management', matched: true, confidence: 0.95 },
      { name: 'Risk Management', matched: true, confidence: 0.93 },
      { name: 'Primavera P6', matched: true, confidence: 0.88 },
      { name: 'Budget Control', matched: true, confidence: 0.9 },
      { name: 'FIDIC Contracts', matched: true, confidence: 0.92 },
    ],
    certifications: ['PMP', 'MSP', 'RICS'],
    status: 'shortlisted',
    finalScore: 86,
    criterionScores: {
      yearsExperience: { score: 90, justification: '23 years experience — strong, though role seniority may be mismatched (Director vs Manager).' },
      technicalSkills: { score: 90, justification: 'All required skills evidenced. FIDIC and Primavera P6 specifically mentioned.' },
      industryBackground: { score: 85, justification: 'Abu Dhabi government projects are prestigious but differ from private real estate development.' },
      certifications: { score: 88, justification: 'PMP + MSP + RICS — very strong but PRINCE2 absent.' },
      languages: { score: 72, justification: 'English and French — no Arabic is a gap for Abu Dhabi government client work.' },
    },
    aiSummary:
      'David is a highly capable PM professional with extensive GCC experience. His Hill International background on Abu Dhabi government programmes is impressive. Potential concern: he may be overqualified at Director level and seeking a step down, which should be explored in interview.',
    extractionConfidence: 0.94,
    shortlistedAt: '2024-11-11T10:00:00Z',
    createdAt: '2024-11-10T09:00:00Z',
    cvFilePath: 'cvs/david-okafor.pdf',
  },
]

// ─── CANDIDATES — Job 003 (Quantity Surveyor) ────────────────────────────────

export const mockCandidatesJob003: Candidate[] = [
  {
    id: 'cand-201',
    jobProfileId: 'job-003',
    name: 'Aisha Binti Hamdan',
    email: 'aisha.hamdan@qs.com',
    phone: '+971 50 234 5678',
    nationality: 'Malaysian',
    age: 35,
    languages: ['English', 'Malay', 'Arabic'],
    currentTitle: 'Senior Quantity Surveyor',
    currentCompany: 'Turner & Townsend',
    yearsExperience: 11,
    degreeLevel: 'bachelor',
    degreeField: 'Quantity Surveying',
    education: [
      {
        institution: 'Universiti Teknologi Malaysia',
        degree: 'Bachelor of Science (Hons)',
        field: 'Quantity Surveying',
        year: 2013,
        grade: 'First Class',
      },
    ],
    experience: [
      {
        company: 'Turner & Townsend',
        title: 'Senior Quantity Surveyor',
        startDate: '2019-04',
        endDate: null,
        duration: '5 yr 7 mo',
        description: 'Cost management on Dubai Metro Blue Line extension — AED 12B programme.',
      },
      {
        company: 'Mott MacDonald',
        title: 'Quantity Surveyor',
        startDate: '2015-01',
        endDate: '2019-03',
        duration: '4 yr 2 mo',
      },
      {
        company: 'Ranhill SAJ',
        title: 'Junior QS',
        startDate: '2013-07',
        endDate: '2014-12',
        duration: '1 yr 5 mo',
      },
    ],
    skills: [
      { name: 'Cost Estimation', matched: true, confidence: 0.96 },
      { name: 'Contract Administration', matched: true, confidence: 0.94 },
      { name: 'CostX / Candy', matched: true, confidence: 0.92 },
      { name: 'Value Engineering', matched: true, confidence: 0.88 },
    ],
    certifications: ['RICS MRICS', 'AIQS'],
    status: 'shortlisted',
    finalScore: 93,
    criterionScores: {
      yearsExperience: { score: 90, justification: '11 years in QS, exactly within the 5-15 year range. Turner & Townsend is tier-1 consultancy.' },
      technicalSkills: { score: 95, justification: 'All four preferred skills present with strong evidence on a landmark infrastructure project.' },
      industryBackground: { score: 92, justification: 'UAE Metro infrastructure — directly aligned with the infrastructure QS role.' },
      certifications: { score: 97, justification: 'MRICS certified — the gold standard for quantity surveying. AIQS is a bonus.' },
      languages: { score: 88, justification: 'Trilingual including Arabic — significant advantage for GCC contracting.' },
    },
    aiSummary:
      'Aisha is an outstanding QS candidate with MRICS accreditation and direct UAE infrastructure experience at Turner & Townsend. Her Dubai Metro Blue Line cost management work is precisely the profile sought. Highly recommended for shortlisting.',
    extractionConfidence: 0.97,
    shortlistedAt: '2024-11-01T09:00:00Z',
    createdAt: '2024-10-31T08:00:00Z',
    cvFilePath: 'cvs/aisha-hamdan.pdf',
  },
]

// ─── ALL CANDIDATES MAP ─────────────────────────────────────────────────────

export const mockCandidatesByJob: Record<string, Candidate[]> = {
  'job-001': mockCandidatesJob001,
  'job-002': mockCandidatesJob002,
  'job-003': mockCandidatesJob003,
}

export const allMockCandidates: Candidate[] = [
  ...mockCandidatesJob001,
  ...mockCandidatesJob002,
  ...mockCandidatesJob003,
]

// ─── WHATSAPP THREADS ───────────────────────────────────────────────────────

export const mockWhatsAppThreads: WhatsAppThread[] = [
  {
    id: 'thread-001',
    candidateId: 'cand-001',
    candidateName: 'Ahmed Al-Rashidi',
    candidateInitials: 'AA',
    jobProfileId: 'job-001',
    jobTitle: 'Senior Site Engineer',
    phoneNumber: '+971 50 123 4567',
    status: 'follow_up',
    lastMessage: 'Yes, I am available for an interview next week. Tuesday or Wednesday works best for me.',
    lastMessageAt: '2024-11-16T14:32:00Z',
    unread: true,
    candidateScore: 91,
    messages: [
      {
        id: 'msg-001-1',
        threadId: 'thread-001',
        direction: 'outbound',
        content: 'Hello Ahmed! We reviewed your application for the Senior Site Engineer position at our company and were very impressed. We\'d love to schedule a brief screening call. Are you available this week or next?',
        messageType: 'template',
        sentAt: '2024-11-16T09:00:00Z',
        deliveredAt: '2024-11-16T09:01:00Z',
        readAt: '2024-11-16T11:30:00Z',
      },
      {
        id: 'msg-001-sys-1',
        threadId: 'thread-001',
        direction: 'outbound',
        content: 'Screening questions sent',
        messageType: 'screening',
        sentAt: '2024-11-16T09:00:00Z',
        isSystemEvent: true,
      },
      {
        id: 'msg-001-2',
        threadId: 'thread-001',
        direction: 'inbound',
        content: 'Thank you for reaching out! I am very interested in this opportunity. I have been with ALEC for 5 years and am looking for new challenges. What are the next steps?',
        messageType: 'free_text',
        sentAt: '2024-11-16T11:35:00Z',
        deliveredAt: '2024-11-16T11:35:00Z',
      },
      {
        id: 'msg-001-3',
        threadId: 'thread-001',
        direction: 'outbound',
        content: 'Excellent, Ahmed! The next step would be a 30-minute video call with our technical lead. We would discuss the role requirements, your experience on high-rise projects, and any questions you may have. Would that work for you?',
        messageType: 'free_text',
        sentAt: '2024-11-16T12:00:00Z',
        deliveredAt: '2024-11-16T12:01:00Z',
        readAt: '2024-11-16T14:30:00Z',
      },
      {
        id: 'msg-001-4',
        threadId: 'thread-001',
        direction: 'inbound',
        content: 'Yes, I am available for an interview next week. Tuesday or Wednesday works best for me.',
        messageType: 'free_text',
        sentAt: '2024-11-16T14:32:00Z',
        deliveredAt: '2024-11-16T14:32:00Z',
      },
    ],
  },
  {
    id: 'thread-002',
    candidateId: 'cand-003',
    candidateName: 'Omar Khalil',
    candidateInitials: 'OK',
    jobProfileId: 'job-001',
    jobTitle: 'Senior Site Engineer',
    phoneNumber: '+971 52 456 7890',
    status: 'screening',
    lastMessage: 'Hello Omar! We reviewed your application for the Senior Site Engineer role...',
    lastMessageAt: '2024-11-16T10:00:00Z',
    unread: false,
    candidateScore: 88,
    messages: [
      {
        id: 'msg-002-1',
        threadId: 'thread-002',
        direction: 'outbound',
        content: 'Hello Omar! We reviewed your application for the Senior Site Engineer role and your experience on landmark Abu Dhabi projects caught our attention. We would like to schedule a screening call. Are you currently exploring opportunities?',
        messageType: 'template',
        sentAt: '2024-11-16T10:00:00Z',
        deliveredAt: '2024-11-16T10:01:00Z',
      },
      {
        id: 'msg-002-sys-1',
        threadId: 'thread-002',
        direction: 'outbound',
        content: 'Initial outreach sent',
        messageType: 'screening',
        sentAt: '2024-11-16T10:00:00Z',
        isSystemEvent: true,
      },
    ],
  },
  {
    id: 'thread-003',
    candidateId: 'cand-101',
    candidateName: 'Sarah Al-Mansoori',
    candidateInitials: 'SA',
    jobProfileId: 'job-002',
    jobTitle: 'Project Manager',
    phoneNumber: '+971 50 456 7890',
    status: 'follow_up',
    lastMessage: 'I have attached my updated references as requested. Looking forward to hearing from you.',
    lastMessageAt: '2024-11-12T16:45:00Z',
    unread: false,
    candidateScore: 95,
    messages: [
      {
        id: 'msg-003-1',
        threadId: 'thread-003',
        direction: 'outbound',
        content: 'Hi Sarah! Your profile for our Project Manager role is outstanding. We would love to fast-track you to a technical interview with our CEO. Are you available for a call this week?',
        messageType: 'template',
        sentAt: '2024-11-11T09:00:00Z',
        deliveredAt: '2024-11-11T09:01:00Z',
        readAt: '2024-11-11T09:15:00Z',
      },
      {
        id: 'msg-003-2',
        threadId: 'thread-003',
        direction: 'inbound',
        content: 'Thank you! I am very interested. I am available Thursday afternoon or Friday morning this week.',
        messageType: 'free_text',
        sentAt: '2024-11-11T09:20:00Z',
      },
      {
        id: 'msg-003-3',
        threadId: 'thread-003',
        direction: 'outbound',
        content: 'Perfect! I have scheduled a video call for Thursday at 2:00 PM UAE time with our CEO and HR Director. You will receive a calendar invite shortly. Please also bring or share your last 3 project references.',
        messageType: 'free_text',
        sentAt: '2024-11-11T10:00:00Z',
        deliveredAt: '2024-11-11T10:01:00Z',
        readAt: '2024-11-11T10:30:00Z',
      },
      {
        id: 'msg-003-4',
        threadId: 'thread-003',
        direction: 'inbound',
        content: 'I have attached my updated references as requested. Looking forward to hearing from you.',
        messageType: 'free_text',
        sentAt: '2024-11-12T16:45:00Z',
      },
    ],
  },
  {
    id: 'thread-004',
    candidateId: 'cand-201',
    candidateName: 'Aisha Binti Hamdan',
    candidateInitials: 'AB',
    jobProfileId: 'job-003',
    jobTitle: 'Quantity Surveyor',
    phoneNumber: '+971 50 234 5678',
    status: 'screening',
    lastMessage: 'Screening questions sent — awaiting response',
    lastMessageAt: '2024-11-01T10:00:00Z',
    unread: false,
    candidateScore: 93,
    messages: [
      {
        id: 'msg-004-1',
        threadId: 'thread-004',
        direction: 'outbound',
        content: 'Hi Aisha! We came across your profile for our Senior QS opening. Your MRICS certification and Dubai Metro experience are exactly what we\'re looking for. Could you spare 15 minutes for a quick screening call?',
        messageType: 'template',
        sentAt: '2024-11-01T09:00:00Z',
        deliveredAt: '2024-11-01T09:01:00Z',
      },
      {
        id: 'msg-004-sys-1',
        threadId: 'thread-004',
        direction: 'outbound',
        content: 'Screening questions sent',
        messageType: 'screening',
        sentAt: '2024-11-01T09:00:00Z',
        isSystemEvent: true,
      },
    ],
  },
]

// ─── NOTIFICATIONS ──────────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'whatsapp_reply',
    title: 'Ahmed Al-Rashidi replied',
    message: 'Yes, I am available for an interview next week...',
    read: false,
    createdAt: '2024-11-16T14:32:00Z',
    href: '/whatsapp',
  },
  {
    id: 'notif-002',
    type: 'scoring_complete',
    title: 'Scoring complete: Senior Site Engineer',
    message: '24 candidates scored. 8 shortlisted.',
    read: false,
    createdAt: '2024-11-15T16:00:00Z',
    href: '/jobs/job-001/results',
  },
  {
    id: 'notif-003',
    type: 'upload_complete',
    title: 'Upload complete: Project Manager',
    message: '31 CVs uploaded and queued for scoring.',
    read: true,
    createdAt: '2024-11-10T11:00:00Z',
    href: '/jobs/job-002/upload',
  },
  {
    id: 'notif-004',
    type: 'scoring_complete',
    title: 'Scoring complete: Project Manager',
    message: '31 candidates scored. 9 shortlisted.',
    read: true,
    createdAt: '2024-11-10T14:30:00Z',
    href: '/jobs/job-002/results',
  },
  {
    id: 'notif-005',
    type: 'whatsapp_reply',
    title: 'Sarah Al-Mansoori sent references',
    message: 'I have attached my updated references...',
    read: true,
    createdAt: '2024-11-12T16:45:00Z',
    href: '/whatsapp',
  },
]

// ─── CHAT MOCK RESPONSES ────────────────────────────────────────────────────

export const mockChatResponses: Record<string, string> = {
  'What are the key gaps for this role?':
    'Based on the scoring breakdown, the main gaps for this candidate relative to the Senior Site Engineer role are:\n\n1. **Primavera P6** — Not mentioned in the CV. The role requires scheduling proficiency, and this is weighted at 30% of technical skills.\n2. **FIDIC Certification** — Listed as mandatory but not held. This alone would normally trigger elimination, but extraction confidence on certifications was moderate.\n3. **Arabic Language** — The candidate is English-only, which limits effectiveness in UAE client-facing scenarios.\n\nThese gaps account for the difference between the candidate\'s raw technical ability (strong) and their final composite score.',

  'Summarize leadership experience':
    'This candidate has demonstrated progressive leadership responsibility across their career:\n\n- **Current role**: Leading a team of 8 engineers on a multi-tower residential project\n- **Previous role**: Supervised subcontractor teams of up to 40 workers on villa community developments\n- **Notable**: No formal people management training mentioned, but operational leadership is evidenced through project scale\n\nLeadership experience is solid for a senior individual contributor role but may need bolstering for a managerial step-up.',

  'How does this candidate compare to average shortlisted?':
    'Comparison against the 8 shortlisted candidates for this role:\n\n| Metric | This Candidate | Shortlist Average |\n|--------|---------------|-------------------|\n| Overall Score | 88 | 81 |\n| Years Experience | 17 yr | 12 yr |\n| Technical Skills | 82 | 79 |\n| Certifications | 90 | 76 |\n\nThis candidate scores **above average** on all dimensions. They rank **2nd overall** in the shortlist, behind Ahmed Al-Rashidi (91).',

  'Are there any red flags?':
    'The AI analysis flagged the following items for human review:\n\n1. **Employment gap** — A 4-month gap between Arabtec and the current role (Jun–Oct 2018) is unexplained in the CV. Worth asking about.\n2. **Frequent company changes** — 3 companies in 6 years early in career, though this stabilised in the last position.\n3. **Reference credibility** — All listed references appear to be direct reports rather than supervisors. This is atypical and may warrant follow-up.\n\nNone of these are disqualifying, but they warrant direct questions in the screening call.',

  'Is this candidate likely overqualified?':
    'Overqualification risk: **Moderate**\n\nFactors suggesting overqualification:\n- 17 years of experience vs. 8-year minimum requirement\n- Currently managing projects at a higher level than the posted role\n- Likely earning above the standard band for this position\n\nFactors mitigating the risk:\n- UAE market often has experienced professionals seeking role stability over title progression\n- Construction sector frequently sees lateral moves\n- Nothing in the CV or summary suggests explicit upward career trajectory demands\n\n**Recommendation**: Include a direct question about salary expectations and career trajectory in the screening call.',
}

export const mockShortlistChatResponses: Record<string, string> = {
  'Compare top 3 candidates':
    'The top 3 candidates for Senior Site Engineer based on composite scores:\n\n**1. Ahmed Al-Rashidi (91/100)** — Emirati, 14 yr exp, ALEC Engineering. Best-in-class industry alignment and bilingual.\n\n**2. Omar Khalil (88/100)** — Egyptian, 17 yr exp, Six Construct. Strongest experience depth; slight gap in BIM.\n\n**3. Priya Nair (82/100)** — Indian, 9 yr exp, Shapoorji. Best BIM skills; gap in language and Primavera P6.\n\n**Recommendation**: Interview all three. Ahmed and Omar for senior execution roles; Priya for BIM-heavy delivery tracks.',

  'Who has the best cultural fit for UAE clients?':
    'Across the 8 shortlisted candidates, **Ahmed Al-Rashidi** scores highest for UAE cultural fit:\n\n- Emirati nationality (priority for UAE government client work)\n- Native Arabic speaker\n- Educated in UAE\n- Entire career within UAE\n\nSecond-best: **Omar Khalil** (Egyptian/Arabic-speaking with long UAE tenure)\n\nFor international developer clients (e.g., DAMAC, Nakheel), **James Whitmore** or **Priya Nair** may be preferred for English-first client engagement.',
}

// ─── MESSAGE TEMPLATES ──────────────────────────────────────────────────────

export const mockMessageTemplates = [
  {
    id: 'tmpl-001',
    name: 'Initial Outreach',
    content:
      'Hi {{name}}, we came across your profile for our {{role}} opening at {{company}}. Your background in {{highlight}} stood out to us. Are you currently open to new opportunities?',
  },
  {
    id: 'tmpl-002',
    name: 'Interview Invitation',
    content:
      'Hi {{name}}, we\'d love to invite you for a {{type}} interview for the {{role}} position. Are you available {{date_options}}?',
  },
  {
    id: 'tmpl-003',
    name: 'Screening Questions',
    content:
      'Hi {{name}}, thank you for your interest. Before we schedule a call, could you briefly answer: 1) Current notice period? 2) Salary expectations? 3) Are you open to relocation to {{location}}?',
  },
  {
    id: 'tmpl-004',
    name: 'Follow-up',
    content:
      'Hi {{name}}, just following up on my earlier message. We\'re moving quickly on this role and would love to connect. Are you available for a quick 15-minute call this week?',
  },
]

// ─── JOB TITLE TEMPLATES ─────────────────────────────────────────────────────

export const jobTitleTemplates = [
  'Site Engineer',
  'Senior Site Engineer',
  'Project Engineer',
  'Project Manager',
  'Senior Project Manager',
  'Quantity Surveyor',
  'Senior Quantity Surveyor',
  'Construction Manager',
  'Civil Engineer',
  'Structural Engineer',
  'MEP Engineer',
  'HSE Manager',
  'Planning Engineer',
  'Contract Manager',
]

// ─── SCORING WEIGHT PRESETS ──────────────────────────────────────────────────

export const scoringPresets = {
  balanced: {
    yearsExperience: 20,
    technicalSkills: 25,
    industryBackground: 20,
    certifications: 20,
    languages: 15,
  },
  experienceHeavy: {
    yearsExperience: 40,
    technicalSkills: 25,
    industryBackground: 20,
    certifications: 10,
    languages: 5,
  },
  skillsHeavy: {
    yearsExperience: 15,
    technicalSkills: 50,
    industryBackground: 15,
    certifications: 15,
    languages: 5,
  },
}
